name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell

      - name: Run install packages
        run: npm install

      - name: Run build
        run: npm build

          #- name: Run check-types
          #run: npm run check:types

          #- name: Run lint
          #run: npm run lint

          #- name: Run tests
          #run: npm test
