name: Test coverage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    # NOTE: Not yet working in container:
    # container: node:latest
    steps:
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell

        #- name: Install packages marked as dependencies
        #run: yarn

      - uses: artiomtr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
            #skip-step: install
          threshold: 1
          test-script: yarn test:coverage
